
spring:
  profiles:
    active: local

---
spring:
  profiles: local

  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 500
    hibernate:
      ddl-auto: create-drop
    database-platform: H2

  h2:
    console:
      enabled: false
#  main:
#    lazy-initialization: true


logging:
  level:
    root: info
    org.springframework.org: info
    com.ms.kp: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.data.redis: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
  file:
    path: log/sharemoney
